apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: http-ace-flow
  namespace: cp4i-162
spec:
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProduction

  version: '13.0.0.0-r1'
  replicas: 1

  barURL: 
    - "http://192.168.1.35:8081/repository/tekton-hosted-repo/Http_Ace_flow.bar"

  env:
    - name: ODBCINI
      value: /home/aceuser/ace-server/odbc.ini
    - name: LD_LIBRARY_PATH
      value: /opt/ibm/ace-12/server/ODBC/dsdriver/odbc_cli/clidriver/lib
    - name: IE02_PATH
      value: /opt/ibm/ace-12/ieo2

  configurations:
    - ace-odbcini
    - ace-setdbparms
    - nexus-barauth
